### ISSUE TITLE
Issue with stable build

### ISSUE THREAD

**Issue by rishab-alt** [Heavy-Division/B78XH#100]
main flight display and nav display keep freezing
![Screenshot 2021-07-02 112915](https://user-images.githubusercontent.com/60842647/124261477-bf531500-db28-11eb-9d90-7bd3883d19a1.png)

**Comment by alecdurberville** [comment]
same!  displays freeze but aircraft continues on programmed flight plan (as shown in navigraph window)
![image](https://user-images.githubusercontent.com/87395987/125528549-849ca008-d34f-4114-a7a1-62bf408958b8.png)

**Comment by kimlada** [comment]
You have outdated version... use version 0.1.9 or DEV build
