### ISSUE TITLE
MOD does not install

### ISSUE THREAD

**Issue by picklertune** [Heavy-Division/B78XH#101]
I have extracted the stable version in communities however nothing happens when i load the default 787. I tried the experimental version as well and it also did not take effect. In content manager i see the mod as installed.

**Comment by lmk02** [comment]
So you did try this (https://github.com/Heavy-Division/B78XH/archive/refs/heads/WTFPMMEPOC.zip) version? Do you have any additional mods installed?

**Comment by dsuresh-ap** [comment]
I tried installing `master` and it didn't seem to show up in the sim. The default 787 loaded. Installing v0.1.9 worked though.

**Comment by picklertune** [comment]
yes for me as well old version works fine but latest version does not install

**Comment by kimlada** [comment]
Closing -> old issue
