### ISSUE TITLE
SU5 Issues

### ISSUE THREAD

**Issue by benegnt** [Heavy-Division/B78XH#106]
Hey, anyone else finding that MSFS is crashing to desktop when using this mod following sim update 5?  Have tested it without the mod and the 78X loads fine, with the mod is crashes.  Is anyone else is experiencing the same?  Thanks.

**Comment by benegnt** [comment]
Just to add, this clearly isn't an issue caused by Heavy-Division, Asobo/Microsoft have caused these issues with the major failings in SU5.  I would imagine the team here will be waiting for some form of hot-fix from Asobo then updating this mod which was working very well prior to the latest Sim update.  Just hoping that the team here have some time to update ASAP once the hotfix is released as this is an amazing mod and is the only thing that makes the 787 worth flying.

**Comment by Jmsoo** [comment]
Hi my sim just work fine no crashes so far! I wanted actually to test this mod on a 4 hours plus flight but I have the IRS not alligning anymore since the new FS2020

**Comment by roadrunner06** [comment]
I do use XH mod in sim it can fly and not CTD but my ND PFD display are screwed and unable to see my flight plan as i cannot unzoom the nd formsome reason by try to take off yesterday its ok.

**Comment by roadrunner06** [comment]
Also engine display is blank nk number so cannot see what happened with the throttle

**Comment by CsabaKafka** [comment]
I have currently issues with the IRS. The IRS is not alligning.

**Comment by benegnt** [comment]
Hey, if you download the most recent code for this mod the team have made it compatible with sim update 5 (thanks guys).  There is also a hot fix out for the sim as of 15:00 UTC today.  I've done a couple of hours testing and so far looking good!

**Comment by roadrunner06** [comment]
Thank You seems its working now on displays trying out the overall experience hope it's back to normal
