### ISSUE TITLE
guys, go read this. they've totally screwed this sim up

### ISSUE THREAD

**Issue by k8cpachuck** [Heavy-Division/B78XH#107]
[https://forums.flightsimulator.com/t/sim-update-v-1-18-13-0-bug-megathread/426509/285?u=k8cpachuck](url)

**Comment by vstaritz** [comment]
this isn't the place to post your rant that hasn't got anything to do with the mod or provide any information on the issue

**Comment by kimlada** [comment]
Closing -> irrelevant
