### ISSUE TITLE
Can't program flight plan

### ISSUE THREAD

**Issue by Skkkitzo** [Heavy-Division/B78XH#109]
Starting cold and dark, I am unable to select a STAR/runway or SID/runway. On top of that, when I input departure and arrival airport, and execute the flight plan it does not show it using the VFR map.

Using the development build, NOT the release. SU5 is probably the cause.

**Comment by benegnt** [comment]
Hi, ref the STAR/Runway etc, download the latest AIRAC cycle from the Navigraph Navdata Centre, that fixes the issue.  Ref the flight plan not showing on the VFR map, agree, that has been an issue for a couple of months now.  Haven't found a workaround yet.

**Comment by Skkkitzo** [comment]
Correction: I am ABLE to select a STAR/SID but it doesn't show in the flight plan nor the VFR map.

**Comment by kimlada** [comment]
Closing -> old issue
