### ISSUE TITLE
PFD stays unaligned

### ISSUE THREAD

**Issue by patrick75008** [Heavy-Division/B78XH#110]
after sim update 5 : PFD is not working.
Community folder contains only A320X
![787 after sim update 5 don't show up ](https://user-images.githubusercontent.com/59117444/127783465-75b40bda-4b1f-46ab-8f1f-d0a7aaec3cff.png)

**Comment by Tudeski2004** [comment]
I have the same issue. I have removed the entire community folder to see if that helped, and nothing.

**Comment by Saddy768** [comment]
i  have also have an issue PFD is not working even when IRS are all aligned not unable to fly it anymore

**Comment by kimlada** [comment]
This was SU compatibility problem.
