### ISSUE TITLE
unable to start B787 heavy engines from cold and dark

### ISSUE THREAD

**Issue by ejy11** [Heavy-Division/B78XH#111]
since that last update(July27, 2021) I am unable to start the engines. Any help would be appreciated.

**Comment by rabsp9** [comment]
What symptoms are you getting?
Fuel on from overhead and cut/run switches on?
Does Ctrl_E start the engines for you?

**Comment by walt787** [comment]
You would need the APU turned on. However, there seems to be a bug affecting the default 787 where the APU doesn't switch on if the centre fuel tanks switches are in the on position. You'd have to make sure they are in the off position before switching on APU.

**Comment by kimlada** [comment]
Both problems with starting engines are default asobo bug:

1) You have to have LEFT CENTER FUEL PUMP turned off or in PRESS state to be able to run APU
2) CUT OFF swithes does not work -> You have to update premium deluxe content in content manager
