### ISSUE TITLE
Wrong ILS frequency on EHAM runway 06

### ISSUE THREAD

**Issue by Thau** [Heavy-Division/B78XH#115]
Hello, first of all I think this might be a sim issue instead of a mod issue, but just in case I'm reporting it.

When flying to Amsterdam EHAM, if you set your arrival to ILS on runway 06, the ILS radio will be tuned to the wrong frequency and the approach will fail unless you tune it manually.

To reproduce easily start a flight in a custom waypoint close to Amsterdam, then set the flight plan to end in EHAM, with any approach to ILS 06. Let the plane fly there, and check how the glideslope is correct, but the localizer fails because it belongs to a different runway.

Thank you for your hard work!

**Comment by kimlada** [comment]
Actually MSFS do not tune any frequency when i use ILS 06... So it is probably a NavData problem...
