### ISSUE TITLE
MCP Range Knob Does Not Zoom In or Out

### ISSUE THREAD

**Issue by OliveBeast20441** [Heavy-Division/B78XH#116]
This is due to the SU5 changes, as it was working before.

However, the range knob on the MCP has no zoom in/ out effect when rotated. The range is fixed to the airport diagram, probably somewhere between 2-5nm.  There are no other mods installed in my Community folder; only the B78XH mod.

Thanks to everyone who continues to work on this mod.  Before SU5, this aircraft was a joy to fly!

**Comment by nakajimayoshi** [comment]
If the issue persists, please resubmit as a new issue with video. Thanks
