### ISSUE TITLE
Engine Values At Zero on MFD When Aircraft is Loaded on a Runway

### ISSUE THREAD

**Issue by OliveBeast20441** [Heavy-Division/B78XH#117]
This is due to the SU5 changes, as it was working before.

The engine parameters on the MFD read zero, despite the fact that the engines are running. There are no other mods installed in my Community folder; only the B78XH mod.

**Comment by kimlada** [comment]
Do you have updated everything in your content manager??

**Comment by OliveBeast20441** [comment]
Yes, the content manager is updated. This only happens when loading the aircraft on the runway. If I start cold & dark at the gate, the engines spool up normally and all indications are good.

**Comment by Toninhodj2007** [comment]
O IRS não faz o alinhamento e os indicadores do motor também permanecem sem funcionar.

**Comment by Toninhodj2007** [comment]
No meu caso está tudo atualizado no gerenciador de conteúdo

**Comment by kimlada** [comment]
Closing -> old issue
