### ISSUE TITLE
Flap Position Does Not Move When Aircraft is Loaded on the Runway

### ISSUE THREAD

**Issue by OliveBeast20441** [Heavy-Division/B78XH#118]
This is due to the SU5 changes, as it was working before.

Oddly enough, the flap position works when started from cold & dark, at the gate, but is fixed at 15 degrees when the aircraft is loaded on a runway with engines running.  There are no other mods installed in my Community folder; only the B78XH mod.

**Comment by kimlada** [comment]
Closing -> old issue
