### ISSUE TITLE
RNAV don't work.

### ISSUE THREAD

**Issue by karol-leszczynski** [Heavy-Division/B78XH#121]
There are no indicators visible and no Flight Director reaction for RNAV approach.

**Comment by TDiver1715** [comment]
Hello.   GREAT addition for the B787!  

I too have no RNAV capability unfortunately.  I have shot RNAV approaches (including LPV, etc)_ at multiple airports with no success.  When I remove the B78XH directory from my Community folder, the capability returns to the "stock" B787.  I tried lots of fault analysis with no luck, to include a "clean" Community folder and no other scenery add-ons via the Marketplace with the same result.  

When I am entering the RNAV LPV  path, I press the APPROACH button at IAF to intercept/lock the G/P.  The PFD then displays  "LOC" and "G/S" (ILS info) vice the expected RNAV VNAV G/P info.  In addition, the aircraft AP is disconnected from the FMS and "does its own thing".  I'm no programming, but it appears to be trying ILS vice RNAV approach,

I hope this info is helpful and greatly look forward to future updates!  If I can be of any help, let me know!

Best Regards,
Mike aka "TDiver1715"

**Comment by TDiver1715** [comment]
Here are some screenshots for my post last night above.

Stock 787 showing FAC + G/P for RNAV Approach:
![Stock FMC GP Showing](https://user-images.githubusercontent.com/91804530/135763583-dbd77dac-7a62-4237-9a94-7b29e9b48478.jpg)

787 MOD showing LOC + G/S for RNAV Approach (showing ILS for RNAV):
![RNAV Approach - Shows ILS LOC+GS vice RNAV FAC+GP](https://user-images.githubusercontent.com/91804530/135763630-645731f4-b036-4fef-9cd8-d6ef91868a10.jpg)

I hope these are helpful!

**Comment by kimlada** [comment]
RNAV is not supported at this time...
