### ISSUE TITLE
Deleting a way point insert a waypoint delet

### ISSUE THREAD

**Issue by nwenkel** [Heavy-Division/B78XH#123]
The FPM seems to be messed up when using the Main version. E.g. deleting a way point insert a waypoint DELET which can not be deleted.

**Comment by dadrocker** [comment]
Having the same problem.. Downloaded and builded last main....

**Comment by karol-leszczynski** [comment]
It seams to be some bug. As for now, to workaround that, when "delet" waypoint list pops up, you can go back in menu. Don't choose any of "DELET" listed, go back, and the waypoint that you actually wan to delete should be deleted. It worked for me at least...
