### ISSUE TITLE
Step Climb (and descent) in VNAV

### ISSUE THREAD

**Issue by DanP77** [Heavy-Division/B78XH#125]
MOD version 31 August 2021.

Altitude set in FMS VNAV FL340.
Modifying in MCP from 34000 to 36000 for a step climb it does not modify automatically (I'm expecting it) in the FMS, so the airplane does not climb in VNAV.
Changing it in FMS manually, the airplane Climb as requested.

Same behavior in the further step FL360 to FL380.

I'm expecting (I'm not real rated on 787), that the FMS automatically update to the new Cruise level, when modified in MCP over the cruise altitude set on FMS VNAV page.

**Comment by kimlada** [comment]
Step climb is not supported now...

Only CLB CRZ and CRZ DES procedures are supported now.

**Comment by DanP77** [comment]
Ok.
What I mean, that when I push on the Knob with a Level higher than the actual Cruise Level, it has to autoupdate the value on the FMC, so in VNAV, the plane can Climb.

**Comment by DanP77** [comment]
Same problem in Descent.
VNAV mode selected on MCP
If in my FMS is set FL370, and I set a step descent to FL290, pushing on Knob, but nothing happens.

**Comment by DanP77** [comment]
Normal behavior expected:

In Climb:
Till Cruize FL it's ok.
If I set a value over the Cruize FL--> new Cruize FL has to be set in FMS (further optimization could be do not accept value over max altitude)

In Descent
Descent from Cruize FL has to be done only pushing the altitude Knob. (I do not remember now if this modify the FMS, I think no)
