### ISSUE TITLE
Route not displayed on ND when loading from Game

### ISSUE THREAD

**Issue by runningdavid** [Heavy-Division/B78XH#127]
I clicked on "Request Route" then "Request route from SB" and doesn't work. Setting route in game then load into the plane also doesn't work. Please fix, thanks.

**Comment by runningdavid** [comment]
Actually route from game is loaded but doesn't show up on ND for some reason, any idea?

**Comment by runningdavid** [comment]
Loading from SB resumes working for me now. Loading from Game using "OneWay" strategy works but route is still not displayed on ND.

**Comment by kimlada** [comment]
You need to activate route when you use OneWay sync strategy.

Easiest way to do it:

1) Load into game
2) Open LEGS page and do DIRECT TO you active waypoint (first waypoint on LEGS page)
3) Open ROUTE PAGE and click on ACTIVATE prompt (RSK6)
4) Execute the activation by EXEC

**Comment by nakajimayoshi** [comment]
Check the latest version, fp sync via MSFS or SB has been added
