### ISSUE TITLE
White cockpit screens !!!!!

### ISSUE THREAD

**Issue by KIMCAPTAIN** [Heavy-Division/B78XH#130]
Hey can someone help me ? 
All screens (PFD,MFD...) are white in the cockpit
picture is added

![Uten navn](https://user-images.githubusercontent.com/90110585/132118351-153b4cf7-98ae-4b07-836e-33ccee956e00.png)

**Comment by kimlada** [comment]
Livery problem. Your livery probably contains "panel.cfg" file
