### ISSUE TITLE
FMC managed ILS approach speeds are not present

### ISSUE THREAD

**Issue by atoi2008** [Heavy-Division/B78XH#131]
I crashed in to the runway at 280+ knots. There are no FMS managed speeds on the DINGO 5 arrival and ILS 11L approach at KTUS. I just installed the latest master branch today and haven't seen this problem before. 
I will try an approach to a different airport and runway to see if it is global or just specific to that location.

**Comment by fourdragons** [comment]
I just double-checked the official IRL charts for both DINGO 5 and ILS 11L. You are correct that there are no speed constraints. My question is where have you been flying that every STAR and Approach has speed constraints? Speed constraints are the exception, not the rule.

**Comment by atoi2008** [comment]
> I just double-checked the official IRL charts for both DINGO 5 and ILS 11L. You are correct that there are no speed constraints. My question is where have you been flying that every STAR and Approach has speed constraints? Speed constraints are the exception, not the rule.

I'm just going to chalk this up to Pilot Error. :)
