### ISSUE TITLE
Latest stable build released yesterday

### ISSUE THREAD

**Issue by Arcodacalheta** [Heavy-Division/B78XH#132]
Many thanks for your continued support and wonderful work on this 787!
A couple of issues experienced yesterday for your information with the hope it can help:
1/ When taking off (all FMC entries having been input correctly and the airplane properly configured), the A/T would not hold ON (no light), although the PFD was showing the REF properly and the speed was correct for the clean configuration. The speed was going down, I intervened, stabilized my climb, and pushed again the A/T button, still no light on, but the speed held on to where I put it manually (of course the two A/T switches were ON). After a few minutes in the climb, the A/T button light came on, without me doing anything, and remained so during the entire flight.
2/ The altimeter button centre could not be pressed for STD, I could not find where I could press and finally settled for a manual 1013 input.
3/ Upon T/D I entered my new altitude to be reached and the plane did start its descent, but after about two thousand feet, it stopped and the speed started to wind down, until I selected VS and everything went well.
4/ After entering my runway and ILS approach in the FMC - and double checking the frequency -, the plane aligned correctly with the LOC, I selected APPR but the G/S did not start when reaching the fix, neither was the proper information (LOC and G/S remained in white) displayed on the PFD, I had to manually fly the approach which was visual anyway using PAPI lights.
Again thank you to the whole team!

**Comment by kimlada** [comment]
Two new versions were released... Open new issue if you still have the problems.
