### ISSUE TITLE
Flight plan a bit funky

### ISSUE THREAD

**Issue by clintonhankyau** [Heavy-Division/B78XH#133]
Hi HD team, pretty amazing using this mod so far.  Forget about the VNAV for a second, everything seems to work fine on the AP.  I also love how flight plan gets populated into the FMC via SB, however often seeing "route discontinuity" and as I approached the destination airport it seems that the waypoints just disappear.  Really looking forward to a fix with SU6 is out!  Still amazing!

**Comment by fourdragons** [comment]
Better than my last approach with "route discontinuity". Nothing I tried would get it to cycle to the next waypoint. It just kept wanting to go to the last waypoint. So flew to the rest of the waypoints using HDG mode. Works in a pinch, I guess.

**Comment by TDiver1715** [comment]
Similar issue on my last few flights... After TO I enable AP, LNAV, etc.  FMS follows to 1st WP fine, changes course to 2nd WP, proceeds to it, then passes it and never returns.  I also used HDG to get back to the next WP.  After a couple AP disconnects, re-engaging AP, LNAV, etc.,, FMS finally picks up again on the 3rd WP and follows FP from then on.  I can't explain it, but it is recurring now on each flight.

Screenshots below:

![image](https://user-images.githubusercontent.com/91804530/135734601-60019c66-9dfa-436c-8445-9b4511feae16.png)

![image](https://user-images.githubusercontent.com/91804530/135734606-6750357f-ea9e-4929-a8a9-ae8db4aa8750.png)

![image](https://user-images.githubusercontent.com/91804530/135734610-f343fc50-22ab-416a-995f-9c3a247285e9.png)

**Comment by kimlada** [comment]
Closing this because two new versions was released. Please create new issue if you still have the problem.
