### ISSUE TITLE
APU generator status does not show AVAIL

### ISSUE THREAD

**Issue by DarthJahus** [Heavy-Division/B78XH#136]
You turn the APU ON, it blinks FAULT once (probably okay because APU is not on). Then you turn the knob to Start in order to start the APU, you hear it starting and run (correctly), but even if you wait for a long time (_this is the issue_), the status doesn't show AVAIL. You are supposed to wait for that before turning APU GEN L and R on. This issue exists in the default (stock) version of the plane as well (among other related to APU and its pump system, that seem fixed by this mod - yay).

![image](https://user-images.githubusercontent.com/7353366/132948155-3f460427-16dc-4cfc-9fb6-9a3a8aac53a1.png)

**Comment by kimlada** [comment]
This is not possible at this moment.
