### ISSUE TITLE
Altimeter cannot be set to STD

### ISSUE THREAD

**Issue by riotrev** [Heavy-Division/B78XH#138]
Since the last major update in FS2020, I haven't been able to set the altimeter to standard. I have even tried switching back to the legacy mode for the ui controls and still can't click it like you used to be able to.

**Comment by DanP77** [comment]
Duplicate of incident https://github.com/Heavy-Division/B78XH/issues/135

**Comment by kimlada** [comment]
STD can be set by EFIS and last version has also fixed the knob
