### ISSUE TITLE
Aircraft not centered with RWY on ILS approach

### ISSUE THREAD

**Issue by xhemp** [Heavy-Division/B78XH#139]
Great mod, guys, keep going and thanks for that! 
Just flew EBBR - EDDS and even though ILS frequency and LOC (G/S too for that matter) were captured, aircraft wasn't centered at all with the RWY. I was landing on RWY07.
[Video](https://youtu.be/GNbUxt3l4cc) , left until the end to see if it would rectify it to no avail, so I crashed :)
Happy to run any tests if needed.

**Comment by riotrev** [comment]
Same thing happened to my on the 30L approach to OMDB last night

**Comment by xhemp** [comment]
Did a few other flights and they were all fine, will try to fly to EDDS again to see if it's just with that airport and/or was one-off.

**Comment by xhemp** [comment]
It happened again approaching EDDS.

**Comment by fourdragons** [comment]
I'll just add that I've had to hand-fly my approaches (so far) in the B78X. Not a huge deal, except for the height difference with the other planes I hand-fly. LOL ("I know it says I'm 10 feet off the ground, but sure looks like 50 feet to me!")

**Comment by okurz** [comment]
This seems to be an EDDS specific problem reported in https://forums.flightsimulator.com/t/offset-localizer-in-stuttgart-germany-edds/449849 with a workaround available in https://flightsim.to/file/21629/edds-runway-slope-and-ils-fix . This is not a B78XH issue

**Comment by kimlada** [comment]
This is caused by offset... Not a mode problem...
