### ISSUE TITLE
Flight Plan from Simbrief not loading correctly

### ISSUE THREAD

**Issue by Tudeski2004** [Heavy-Division/B78XH#140]
When importing flight plan, the FMC will usually freeze, however when it doesn't, it loads a strange route from the one imported. For instance, a flight from CYVR to NZAA, the route loaded but I found it didn't find most points and added an extra 17000 miles to the plan. You guys are doing a great job, I unfortunately can't flight at the moment, due to the Flight Plan issues, unless there is a way to import the flight plane from the game.

**Comment by kimlada** [comment]
Importer was reworked in last version.
