### ISSUE TITLE
Input Panel Buttons/Colors - Suggestion (Not Bug)

### ISSUE THREAD

**Issue by TDiver1715** [Heavy-Division/B78XH#145]
I would like make a suggestion or perhaps ask if it's possible to change the input panel buttons & lettering colors/contrast?  They are difficult to see for an "older" retired aviator, especially with bright sunlight into the cabin.  

Perhaps something closer to the numbers and alpha input panels on the sides for this one (gray, black & white)?

![image](https://user-images.githubusercontent.com/91804530/135734708-b82f39b6-0072-4aba-8aa0-6de48929e979.png)

My sincere thanks for your hard work and dedication to this project and I look forward to your continued efforts and contributions to making the 787 better and more realistic!!

Best Regards,
TDiver1715

**Comment by kimlada** [comment]
It is possible... I will make some option for changing the colors to more darker...

**Comment by TDiver1715** [comment]
Thank you!!

 

Are you in Korea?  I have been there several times.

 

Your work is great and very much appreciated!

**Comment by kimlada** [comment]
Closing -> FMC changed
