### ISSUE TITLE
When spawning mid-air, Autopilot will not engage LNAV or follow lateral flight path.

### ISSUE THREAD

**Issue by dcherrie** [Heavy-Division/B78XH#147]
When respawning in air due to terrible FPS on long hauls, before yesterdays update the AP would follow LNAV perfectly. Now with the newest updated, the LNAV refuses to engage by pressing it and will only put into standby mode even if you cross the lateral track. Only way to engage it is do a direct to leg however the autopilot does its own thing and doesn't follow the track at all.

https://youtu.be/B6YxLAVt4jE

**Comment by kimlada** [comment]
I would need more information about this... (Syncing configuration, what was set on world map and so on)

**Comment by dcherrie** [comment]
@kimlada FYI issue is still happening.

What I do is respawn in mid-air using the GPS coordinates from Navigraph of the crash point, set that as departure and set the next waypoint as the arrival. I then load in and pause, set my weight, fuel, speed an altitude from what is reported on my StreamDeck.

I then manually input the route because loading from Simbrief mid-air does not work. I've sometimes done it by the Route page and sometimes by the leg page (dependent on how far left of the flight I have to fly).

**Comment by nakajimayoshi** [comment]
@dcherrie Please reupload as a new issue if the problem persists with video
