### ISSUE TITLE
FMC Issues

### ISSUE THREAD

**Issue by Richard-54** [Heavy-Division/B78XH#151]
Can't load SB Flight Plan nor enter Origin of Departure. This is only post update 6.

**Comment by darthstevor** [comment]
Installed the Dev version. import Simbrief works fine thx
But now - HYDraulics page doesnt display. - Changing in STD pressure doesnt work. - Thurst Mode CLB 30° doesnt display onyl 2 dashes

**Comment by 1ancaster** [comment]
Thanks for the update which has successfully restored my Flight Plans from  SimBrief after the problems of MSFS U6. Its great to get the B787XH back into service!

**Comment by npedraon24** [comment]
Hey so I go the same issue after SU7, will the dev version solve this issue for me? (origin and SB)

**Comment by baragoon** [comment]
Hello, anybody home?

**Comment by kimlada** [comment]
This is fixed in DEV and 0.1.11 version
