### ISSUE TITLE
VNAV - A/T behavior

### ISSUE THREAD

**Issue by JimMcl610** [Heavy-Division/B78XH#155]
When engaging the AP with VNAV selected the throttles eventually get to THR REF by first going to idle and then very very slowly increasing.  Similar behavior when selecting FLC.  Makes flying SIDs using the A/P very challenging initially.

**Comment by nakajimayoshi** [comment]
@JimMcl610 For documentation purposes do you mind uploading a video of the problem if it still persists? Thanks

**Comment by JimMcl610** [comment]
Sorry, my post was over a year ago and I have nopt had it installed since then.  As I am now running the beta preview version of MSFS 2020 and I highly doubt the B78XH is keeping pace with the update pace I have no intensions of re-installing it.  If you had asked me a year ago, when I originally posted, you might have stood a chance!

**Comment by nakajimayoshi** [comment]
@JimMcl610 no problem. I will close this issue then.
