### ISSUE TITLE
ND and map screen blank

### ISSUE THREAD

**Issue by Jmoney16** [Heavy-Division/B78XH#156]
With the new update for me the nd screen and map are both blank?

**Comment by kimlada** [comment]
Probably not aligned IRS...

**Comment by Singh673** [comment]
Even get the same thing but for every display screen in the cockpit its just black

**Comment by kimlada** [comment]
> Even get the same thing but for every display screen in the cockpit its just black

Complete black displays are typically caused by outdated liveries. Try to use default MSFS livery.

**Comment by nakajimayoshi** [comment]
Closed due to due extended period. Please reach out to our discord support channel if you require further assistance.
