### ISSUE TITLE
Certain airways do not work

### ISSUE THREAD

**Issue by ryan1336** [Heavy-Division/B78XH#157]
Using latest main branch, I cannot enter the L608 airway to waypoint Logan. Neither manually nor SB import.

You can reproduce this by creating a flightplan on Simbrief from EDDF to EGLL, LOGAN2H arrival. 

Route: SOBR1U SOBRA Y180 BITBU Y181 DEMUL M624 BUB L608 LOGAN

**Comment by kimlada** [comment]
This should be fixed in both DEV and 0.1.11
