### ISSUE TITLE
Same issue after MS UD7 as experienced with UD6 - unable to load FP from Simbrief or to enter From to airports. Also problems with cold and dark start sequence 

### ISSUE THREAD

**Issue by 1ancaster** [Heavy-Division/B78XH#159]
This all seems very similar to previous reports after update 6 but the working update kindly provided and installed then is not working. Also the cold and dark start sequence is bugged. After starting the APU,  the UPU gen does not appear to start because a black out soon follows despite external power apparently connected.
Thanks for all your help - I am bereft without my 787 Heavy and no Salty 747 working either. These two addons and FBWA320NX are the best aircraft available at the moment!
Richard H

**Comment by kimlada** [comment]
Use DEV version or version 0.1.11
