### ISSUE TITLE
Please include in README.md the link to the developer build

### ISSUE THREAD

**Issue by Cassiano-Gunji** [Heavy-Division/B78XH#160]
It would really improve the experience of casual users (not Discord users) if the link to the developer build (https://github.com/Heavy-Division/B78XH/archive/refs/heads/main.zip) was added in the repository description.

**Comment by opr** [comment]
This is just the zip folder for the repository, is this what you had in mind, or is there an actual development _build_ we can download?

**Comment by Cassiano-Gunji** [comment]
Yes, that's the link to the current development build which is mentioned on the Discord channel. And in my experience, it works much better than a clone of the GitHub repository. I'm just suggesting this link to be listed in the front page (readme.md).
