### ISSUE TITLE
Unable to select heading select

### ISSUE THREAD

**Issue by ferrercrew** [Heavy-Division/B78XH#161]
Hi peeps,
Sorry I have checked everywhere but couldn't find the answer, is it me or I am unable to select the heading manually? also the aircraft wont descent or climb when the altitude is altered, I know about the standard pressure it doesn't work but are this settings also non functional? 
Thanks for your help!

**Comment by xhemp** [comment]
Hi!
Have you disabled LNAV when selecting a heading? Have you pushed FL CHG when going on a descent or climb?

**Comment by ferrercrew** [comment]
Hey Xhemp, yes LNAV is not active, even without a Flight Plan I won't be able to select the heading manually.

**Comment by ferrercrew** [comment]
https://user-images.githubusercontent.com/95179011/143775413-23425796-46ad-4a0d-b30c-2382c0240bde.mov

**Comment by xhemp** [comment]
> Hey Xhemp, yes LNAV is not active, even without a Flight Plan I won't be able to select the heading manually.

Weird, indeed, I am preparing another flight here and will test in a bit just to check if I can reproduce it.

**Comment by ferrercrew** [comment]
Let me know then.

Thanks!

**Comment by xhemp** [comment]
> Let me know then.
> 
> Thanks!

Works for me, @ferrercrew , on a flight at the moment EGCC-LFPG and went into heading mode a few times without no issues.

**Comment by ferrercrew** [comment]
https://user-images.githubusercontent.com/95179011/143885309-e60a886b-ad53-41b5-a11a-637bba7acee5.mov

No one else having this issue? what can I do?

Thanks

**Comment by kimlada** [comment]
This is MSFS problem... You have to set "COCKPIT INTERACTION SYSTEM" to "LEGACY" in General Option -> Accessibility

**Comment by ferrercrew** [comment]
@kimlada you are a star, now even the standard pressure works!
Thank you so much!
