### ISSUE TITLE
Head up display zoomed in

### ISSUE THREAD

**Issue by xhemp** [Heavy-Division/B78XH#162]
Great job on this one (0.11.1), it flies very smooth. Just did a quick quick flight between EGLL and EGCC and everything worked as it should.
One thing I noticed though is the head up display is zoomed in which is unusable, don't remember having the same problem on previous versions. 
I will try to get a screenshot shortly (forgot to get one on this quick hop).
Edit: Screenshots added

[Screenshot 1](https://ibb.co/9Nvrq4Q)
[Screenshot 2](https://ibb.co/JqKmm2Z)
[Screenshot 3](https://ibb.co/gr1wfZ8)

**Comment by shubhamvasaikar** [comment]
This is because of MSFS, not this addon. Are you using an ultrawide display?

**Comment by xhemp** [comment]
Interesting, I didn't know. I play on a TV and used to be working fine before (same TV) , that's why I raised this one.

**Comment by kimlada** [comment]
This is problem of SU7...

**Comment by xhemp** [comment]
> This is problem of SU7...

Thanks for confirming, @kimlada . I am closing this one.
