### ISSUE TITLE
Descent and approach issues

### ISSUE THREAD

**Issue by Arcodacalheta** [Heavy-Division/B78XH#165]
On a LFPG-MMMX flight Monday I had an excellent fuel consumption inspire of strong headwinds during almost the entire flight, and a near perfect flight until the very last segment when I prepared for the descent from FL380, first when setting the approach in the FMC, the LNAV would not remain on track anymore (while it was flawless during the whole flight) the plane was moving off-track on the right, I had to use HDG mode, then descent was at first too fast - more than 5'000 ft/mn, suddenly it stopped and would not descend anymore when reaching +/- FL310 (I had FL280 selected), VS would first work, then stopped, I finally had to disconnect the A/P to continue manually my descent and perform the approach that the plane did not want to make on APP selected (ILS23R).
Thanks for your efforts and the wonderful improvements you keep bringing to that plane!

**Comment by rabsp9** [comment]
Checkout my Video series on this, it might help:
Links to 
RAB101 787 Heavy Mod V1 11 1.12 Tutorial Part 1: https://youtu.be/HVarG8AXiTk
RAB101 787 Heavy Mod V1 11 1.12 Tutorial Part 2 https://youtu.be/46Kirg0pwRU
RAB102 787 Heavy Mod V1 11 1.12 Tutorial Holding Patterns: https://www.youtube.com/watch?v=XzYFeZlzHyo
RAB103 787 Heavy Mod V1 11 1.12 Tutorial Holding Patterns: https://youtu.be/h1OOoYAeU-8
RAB105 787 Heavy Mod V1 11 1.12 Tutorial More Holding Patterns a waypoint not in flightpath:https://youtu.be/uLWmIYy8hfY

**Comment by Arcodacalheta** [comment]
Many thanks for those videos Ron, they are most helpful. 

I am using Aivlasoft EFB and I wonder if it plays a role in the problems I am experiencing (it does not with other add-ons though).

Specifically, on three flights, and twice in two days now, I have a random sudden AP disconnection (although it is still lit up), the flight will start spiraling down to the left (always) and I have to take over manually, the A/T works normally, I then use HDG mode to get back on track, climb back to my FL and switch to DIR on my next WPT. 

That does not work each time even though my speed is correct and the LNAV is correctly set.
As said this happens at random times and I cannot see what triggers this phenomenon. Has this been reported as an issue by other simmers?

**Comment by rabsp9** [comment]
Are you flying live weather in the US, I tried that this week and
everything was custard.  I normally fly around Asia and Australia /New
Zealand  where live weather works fine.

If you are on live weather, try to switch to manual and see if that fixes
your issue, the Metar feed into the sim in some places causes really stupid
things to happen.

**Comment by Arcodacalheta** [comment]
Not really Ron. what I described happened in various locations such as the Greenland entoure between UUEE to KORD, over Taiwan entoure from RJAA to VHHH, and approximately 800 NM away from the US West Coast entoure to Japan.
I don't have the feeling this can be related to weather either since the first episode was well before SU7 when the weather was working fine.
It always happens when flying at my cruise level when all parameters are fully stabilised and between WPT, in short, I can't isolate one good reason that would suddenly trigger this event.
I do not experience this with any other airplane (FBW, CJ4, Longitude, GA airplanes - I have not tried the Salty 748 for a while).
On my latest flight from KSFO to RJAA, I could not input my WPT across Pacific, _for example_ 45N145W it would systematically reject the last W and show me a WPT to the East.

PS: As a dog man myself, I loved your two puppies on your videos!!! Superb.

**Comment by nakajimayoshi** [comment]
@Arcodacalheta If the issue still persists please submit a video using the new issues system using the newest DEV version of the mod
