### ISSUE TITLE
Annoying beep sometimes?

### ISSUE THREAD

**Issue by xhemp** [Heavy-Division/B78XH#166]
Does anyone know where this beep comes from? I tried everything and I can't seem to find the culprit, nothing on the ECAM as well

https://user-images.githubusercontent.com/13650956/144302959-91f76154-c73a-4185-a310-e8f848217924.mp4

**Comment by rabsp9** [comment]
Sounds like overspeed

**Comment by xhemp** [comment]
It happens with the plane taxing too.

**Comment by xhemp** [comment]
Still couldn't find out where this is coming from, it happens with the plane just spawned up. Very weird.

**Comment by nakajimayoshi** [comment]
@xhemp if the issue is still occurring please submit a video using the new issue system with the current DEV version of the mod
