### ISSUE TITLE
v0.1.11 incredible by itself.  AutoPilot won't follow flight plan when using VATsim client.

### ISSUE THREAD

**Issue by MRAviator1** [Heavy-Division/B78XH#167]
B78XH mod is incredibly awesome.  many hours full flights SIDs STARs approaches and HOLDS beautiful.  When connected to VATsim via vPilot v2.8.1 or v2.8.4 the AP won't follow the flight plan.  constantly drifts off course.  Since the heavy mod works by itself without VATsim seems it is a vPilot issue but want to bring to your attention.  vPilot does inject VATsim traffic data into MSFS environment as well as change radio frequencies.  Flying MSFS default A320neo flys the same route SID STAR and ILS approach using VATsim vPilot no problem.
Nothing in community folder except B78XH mod.  Windows 10 latest version+patches.  MSFS latest (su7).

Update 12/3/2021:  When I initially submitted this issue on 12/1 I did 5 flights back-to-back KJFK 31L SKOOR4 MERIT ROBUC3 ILS 27  into KBOS.  flights 1,2 without VATsim vPilot and flights went well.  Flight #3 with VATsim and flight would not follow routes.  Flights 4,5 without VATsim flew perfectly.  Today I flew 8 flights same airports and routes mixed results of issues routes not being followed VATsim and without.  I did get a perfect VATsim flight followed all routes only after I quit out of MSFS and started up new.  Perhaps environment variables in MSFS are not being cleared?  I tested this 3 more times and perfect results if I quit MSFS and start up new.

**Comment by nakajimayoshi** [comment]
Closed due to duplicate issue #174
