### ISSUE TITLE
Auto-Deploy of Ground Spoilers Upon Landing Not Working When Armed On Approach

### ISSUE THREAD

**Issue by OliveBeast20441** [Heavy-Division/B78XH#169]
With the latest version installed (0.1.12), the ground spoilers will not deploy upon landing when the spoiler lever is in the "armed" mode  on approach. For now, the workaround is to assign the "deploy spoilers" key assignment to the same joystick button that engages reverse thrust.

**Comment by kimlada** [comment]
This is Asobo bug from SU6... Spoilers lever positions DOWN/ARMED are reversed... (You have to have leveler in DOWN position to auto deploy the spoilers)
