### ISSUE TITLE
Heads up display zoomed in

### ISSUE THREAD

**Issue by Singh673** [Heavy-Division/B78XH#170]
![FlightSimulator_PBuu1bCaeX](https://user-images.githubusercontent.com/7702618/145685331-fc5c6d7a-74c6-41e4-a89f-15662b0b4b94.png)

**Comment by luiscurtolo** [comment]
Why news on this issue?

**Comment by NakajimaYoshi** [comment]
Hello,
This unfortunately was the result of an Asobo update that we cannot change/alter. You can however fix the hud position by adjusting the cockpit camera position using the arrow keys, or resetting the default position in the general settings -> camera menu under 'height' and 'horizontal position'.

**Comment by OUch1164** [comment]
Hello,

Thank you very much for your reply

**Comment by nakajimayoshi** [comment]
Closed due to known issue
