### ISSUE TITLE
APdon't follow the flightplan when strat the approach phase 

### ISSUE THREAD

**Issue by motishow** [Heavy-Division/B78XH#171]
All flight was perfect , but when the plane start the approach  it doesn't follow the flightplan line and got carzy

**Comment by rabsp9** [comment]
> All flight was perfect , but when the plane start the approach it doesn't follow the flightplan line and got carzy

Checkout my Video series on this, it might help:
Links to
RAB101 787 Heavy Mod V1 11 1.12 Tutorial Part 1: https://youtu.be/HVarG8AXiTk
RAB101 787 Heavy Mod V1 11 1.12 Tutorial Part 2 https://youtu.be/46Kirg0pwRU
RAB102 787 Heavy Mod V1 11 1.12 Tutorial Holding Patterns: https://www.youtube.com/watch?v=XzYFeZlzHyo
RAB103 787 Heavy Mod V1 11 1.12 Tutorial Go Arounds: https://youtu.be/h1OOoYAeU-8
RAB105 787 Heavy Mod V1 11 1.12 Tutorial More Holding Patterns a waypoint not in flightpath:https://youtu.be/uLWmIYy8hfY

**Comment by nakajimayoshi** [comment]
Closed due to duplicate issue #168
