### ISSUE TITLE
Cant get in sim flight plan working/Showing

### ISSUE THREAD

**Issue by LordNecton** [Heavy-Division/B78XH#175]
Hi Im new to this mod, I create a flight plan via the in sim world map and i cant get it to show what ever i do the FMC is just blank, Is this a know issue and being worked on?
I only use simbrief to give me a rough fuel plan

**Comment by MRAviator1** [comment]
Hi.  The mod does not use MSFS in sim world map plan.  If you use simbrief you can create a flight plan, generate flight, and import it into the FMS by pressing RTE, Route request, load from SB plan.
