### ISSUE TITLE
Issues with glass cockpit

### ISSUE THREAD

**Issue by Jeffray721** [Heavy-Division/B78XH#181]
Good day all, 

My bad!  I was skiping one step!  Now that I did have a look at the tutorial, I can now manage the FMS properly and the glass cockpit works like a charm!

I tried deleteing this post but could not find a way to achieve it!

**Comment by Jeffray721** [comment]
As explained above...

**Comment by The-VROfficer** [comment]
> Now that I did have a look at the tutorial, I can now manage the FMS properly and the glass cockpit works like a charm!

Hello, I am encountering the same issue and am looking for a fix. What tutorial are you referring to?
