### ISSUE TITLE
LNAV not working

### ISSUE THREAD

**Issue by harrymooneyy** [Heavy-Division/B78XH#183]
I take off and when I select LNAV mode to on it banks to the left and tries to reach a waypoint I have long passed,I'm not sure if this is user error but for now I'm pretty certain it's a bug.

**Comment by kimlada** [comment]
I would really need more information about this problem. Is the aircraft banking to one side when LNAV is activated (donut pattern).

What was your active waypoint?

**Comment by Ray1978perez** [comment]
Hi!! I had the same issue. I take off and when I select LNAV mode to on it banks to the left and tries to reach a waypoint I have long passed,I'm not sure if this is user error but for now I'm pretty certain it's a bug. I appreciate any help...Thanks!!

**Comment by Ray1978perez** [comment]
> I would really need more information about this problem. Is the aircraft banking to one side when LNAV is activated (donut pattern).
> 
> What was your active waypoint?

Hi, I have the same issue, after take off when the plan is supposed to follow the rouge acording the flight plan it start to turn in the wrong way banking in circle. I appreciate any help. Thanks.

**Comment by Ray1978perez** [comment]
> Hi!! I had the same issue. I take off and when I select LNAV mode to on it banks to the left and tries to reach a waypoint I have long passed,I'm not sure if this is user error but for now I'm pretty certain it's a bug. I appreciate any help...Thanks!!
I used to copy in the FMC manually the flight plan from flightaware, i meant doesn' download from.

**Comment by nakajimayoshi** [comment]
Closed due to lack of information from user
