### ISSUE TITLE
APU Shuts Down After About 10 Minutes or So

### ISSUE THREAD

**Issue by mikey-77** [Heavy-Division/B78XH#184]
I love this aircraft, but suddenly the APU started shutting down on me before I could through the checklists to engine start. I have been immediately starting the APU rather than use ground power.

**Comment by dsuresh-ap** [comment]
I noticed this as well, something triggers the APU to shutoff. I think it’s related to fuel pumps but not sure

**Comment by dsuresh-ap** [comment]
So it is by design then @KalTiwana?

**Comment by KalTiwana** [comment]
Yes, it is a design fault. But it should not be the case as in a real 787, the fuel pumps have nothing to do with the operation of the APU.  I hope this helps.

**Comment by KalTiwana** [comment]
The APU shuts down when the centre fuel tank pumps are switched on.  This
is a design fault which should be rectified.  At present, in order to keep
the APU running, leave the centre tank fuel pumps off.


Regards

Kal Tiwana

**Comment by chotaire** [comment]
Does this happen only on B78XH or also on Asobo 787? If the latter, is this something that can be fixed here or does Asobo have to look into this?

**Comment by nakajimayoshi** [comment]
@mikey-77 Are you using the centre fuel pump switches prior to starting the engines?
