### ISSUE TITLE
Fmc flight plan is trying to go back around the world 

### ISSUE THREAD

**Issue by cbrman11** [Heavy-Division/B78XH#185]
I am flying a flight from RKSI TO KSEA and this is the rough I have DCT EGOBA Y697 LANAT Y51 SAMON Y513 KMC DCT DAIGO Y889 PUTER/N0497F370 A590 PLADO DCT PINSO DCT PINTT/N0485F390 DCT PTZGR DCT CHUUK R341 ODK J123 CJAYY B757 KATCH DCT YYJ MARNR7. But after PINTT or PTZGR it trys to fly back around the work to get to CHUUK almost like it thinks the world is a flap map instead of going around is it just me and something I'm doing wrong?

**Comment by benegnt** [comment]
It does show this but the aircraft won't actually turn the other way.  Once you reach the international date line the aircraft will follow the flight plan above and continue east.  It doesn't look good on the map but it will stick to the route (in my experience anyway)

**Comment by nakajimayoshi** [comment]
Closed due to known issue
