### ISSUE TITLE
Flight Plan not Appearing.

### ISSUE THREAD

**Issue by KoplaNum** [Heavy-Division/B78XH#189]
Even after a number of restarts and making sure the configuration is set to [INGAME], the flight plan is not appearing in the FMC
![IOPAURG90](https://user-images.githubusercontent.com/77222925/150672879-b97f3b27-ae35-45fa-9c87-80d7ba288d1e.jpg)
.

**Comment by Ducdirk** [comment]
have the same problem

**Comment by nakajimayoshi** [comment]
@KoplaNum Please ask on the discord support channel if you have issues with the flight plan manager still. 99.9% of the time this is caused by running an outdated version of the mod.
