### ISSUE TITLE
LNAV not followed by the AP 

### ISSUE THREAD

**Issue by Ray1978perez** [Heavy-Division/B78XH#190]
Hi Everyone!! I need some help cause I'm about crazy with it...lol.
I've been doing my first flights on B787-XH and after take off and AP engage, the plane start to turn in the wrong way far from the next point according to the route in the flight plan, example turning or banking to left when the next point is on the right,  prior to desengage the AP i see it flying in circle turning to the airport i took off. Please i appreciate any help!!

**Comment by TDiver1715** [comment]
Hello!  Quick question... do you by chance have the Honeycomb Bravo?

**Comment by Ray1978perez** [comment]
Hello! Thanks for answer my quesitos. My throttle I bought it on ebay. I attached a pic of it.Sent from my T-Mobile 4G LTE Device
-------- Mensaje original --------De: TDiver1715 ***@***.***> Fecha: 31/1/2022  17:12  (GMT-05:00) A: Heavy-Division/B78XH ***@***.***> CC: Ray1978perez ***@***.***>, Author ***@***.***> Asunto: Re: [Heavy-Division/B78XH] LNAV not followed by the AP  (Issue #190) 
Hello!  Quick question... do you by chance have the Honeycomb Bravo?

**Comment by munga2176** [comment]
I'm having the same issue as well....tried the previous version as well and still having the same issues......

**Comment by Ray1978perez** [comment]
Hi friend Unfortunately this is happening, be in touch if hear something about it please let me know. I'm waiting for a long haul or heavy plane for MSFS i could not enjoy this FS as i would like cause i want to fly a not fs default plane , Waiting for pmdg or qualitywings,  and in the mantiene was trying to fly this asobo  B787 but with this issue is making me crazy. Be in touch college. Be in touch. Thanks Sent from my T-Mobile 4G LTE Device
-------- Mensaje original --------De: munga2176 ***@***.***> Fecha: 1/2/2022  23:47  (GMT-05:00) A: Heavy-Division/B78XH ***@***.***> CC: Ray1978perez ***@***.***>, Author ***@***.***> Asunto: Re: [Heavy-Division/B78XH] LNAV not followed by the AP  (Issue #190) 
I'm having the same issue as well....tried the previous version as well and still having the same issues......

**Comment by Ray1978perez** [comment]
Hi!! Next flight i will try to fly it manually without auto pilot for a while, i mean to the 2nd waypoint in the flight plan manually,  then connect it, not the first waypoint as i used to do, and connecting the auto pilot early. Let's see what happend. Sent from my T-Mobile 4G LTE Device
-------- Mensaje original --------De: munga2176 ***@***.***> Fecha: 1/2/2022  23:47  (GMT-05:00) A: Heavy-Division/B78XH ***@***.***> CC: Ray1978perez ***@***.***>, Author ***@***.***> Asunto: Re: [Heavy-Division/B78XH] LNAV not followed by the AP  (Issue #190) 
I'm having the same issue as well....tried the previous version as well and still having the same issues......

**Comment by TheSharedCockpit** [comment]
Hello,

I'm having the same issue (and no I do not have an Honeycomb stuff).

I'll try to **_always_** engage AP after the 2nd waypoint. Could explain why some times it works fine!
Thank you :-)

Didier

**Comment by NakajimaYoshi** [comment]
Hi all, 
AP banking issues 99% of the time are caused by deadzones not being set in simulator. The Boeing AP logic is different from Airbus in that even if AP is on, it will always listen for pilot inputs. So even the slightest nudge/amount of dust/controller dis-calibration can cause this issue.
