### ISSUE TITLE
PFD Altimeter frozen

### ISSUE THREAD

**Issue by Jackaroo05** [Heavy-Division/B78XH#196]
![image](https://user-images.githubusercontent.com/22356378/154763698-d8f66f21-5b77-44c4-bb18-b3db60cb276c.png)
The Pilot and copilot PFD's altimeter is frozen, while the standby works just fine.

Mod Version: v0.1.13
MSFS Version: 1.22.2.0

**Comment by MicahBCode** [comment]
Does this still happen with latest MSFS and B78XH versions? If so, could you give some more details about when it happens and how to reproduce?

**Comment by nakajimayoshi** [comment]
@Jackaroo05 Closed due to out of date version. If your issue is still occurring please resubmit using the new issues system
