### ISSUE TITLE
Can't manually insert new flight plan after completing previous flight

### ISSUE THREAD

**Issue by patryklipski** [Heavy-Division/B78XH#197]
**Steps to reproduce:**
- Program FMC manually
- Fly the entire flight
- Go to POS page and insert new reference airport
- Old route is still programmed in RTE page, and can't even type new ORIGIN airport on that page.

**Expected behaviour:**
- Program FMC manually
- Fly the entire flight
- Go to POS page and insert new reference airport
- Old route is deleted and I can program new one

I'm using develop version at commit: 0f967b0c88cc7e54cdf44771c88428568602e805

**Comment by NakajimaYoshi** [comment]
Hello. Turnarounds are not supported in the current version. You will need to reload the aircraft after landing and parking in order to load a new flight.

Thank you,
Yoshi
