### ISSUE TITLE
ND shows DEBUG-screen

### ISSUE THREAD

**Issue by FRR126** [Heavy-Division/B78XH#210]
Hi, 
Excited to update my 787XH, but ND shows a DEBUG-screen and PD is empty. 
Pls Help :-)

**Comment by dudsha** [comment]
Same for me.

**Comment by benegnt** [comment]
Same for me also.

**Comment by martialblaizot1** [comment]
Same for me...I tried everything I could possibly think of but no way I can get rid of this screen. Let's hope it gets fixed soon. I miss flying this plane :)

**Comment by NakajimaYoshi** [comment]
Hello, this issue is caused when you use the previous SU8 version of the B78XH on the (now released) SU9 version of msfs. Please delete the B78XH file in your community folder and re-download the updated SU9 compatible version.

**Comment by FRR126** [comment]
Thank you, problem is solved!!
Regards.
Piet Bijl
The Netherlands


Van: NakajimaYoshi ***@***.***>
Verzonden: woensdag 27 april 2022 01:56
Aan: Heavy-Division/B78XH ***@***.***>
CC: FRR126 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Heavy-Division/B78XH] ND shows DEBUG-screen (Issue #210)


Hello, this issue is caused when you use the previous SU8 version of the B78XH on the (now released) SU9 version of msfs. Please delete the B78XH file in your community folder and re-download the updated SU9 compatible version.
