### ISSUE TITLE
LNAV malfunctioning? About

### ISSUE THREAD

**Issue by kimidori1000** [Heavy-Division/B78XH#211]
English
Nice to meet you.
I have recently installed this mod and have been playing around with it.
I'd like to get right into it, but even though I have the correct route and settings and the FMC PREFLIGHT COMPLETE text is displayed, I can't press the LNAV button and it says NO ACTIVE ROUTE, so I'm having trouble.
The symptom has occurred multiple times both spawning on the runway and setting from a cold & dark state at the gate.

Could you please let me know if there is a way to address this?

Japanese (native language)
はじめまして。
最近このMODをインストールして遊んでいます。
早速ですがルート設定を正しく設定してFMC PREFLIGHT COMPLETEの文字も表示されているのにLNAVボタンが押せず、NO ACTIVE ROUTEと表示されて困っています。
滑走路でスポーンした時とゲートでコールド＆ダークな状態から設定した時の両方で複数回発生している状況です。

何か対処法があれば教えていただけないでしょうか？

※caution
I used both deepl translate and Google translate to translate the text into English, and re-translated it from Japanese to English to Japanese to make sure there is no discrepancy.I used both deepl translate and Google translate to translate the text into English, and re-translated it from Japanese to English to Japanese so that it would be clear, but I apologize if the meaning is unclear.

![LNAV 1](https://user-images.githubusercontent.com/100519056/163354595-eed3b84e-43a7-46b1-b9e5-fbbc074d0bc0.PNG)
![LNAV 2](https://user-images.githubusercontent.com/100519056/163354560-7a9e022f-ebda-4b0d-b671-a31d08ee05de.PNG)
![LNAV 3](https://user-images.githubusercontent.com/100519056/163354571-a182a67e-780b-41c1-b57b-3a4570a189fe.PNG)
![LNAV 4](https://user-images.githubusercontent.com/100519056/163354583-bc289b8e-5579-464e-a0e1-545b6b879dfe.PNG)
![LNAV 5](https://user-images.githubusercontent.com/100519056/163354590-e26cb1a8-5a4f-43c4-83a7-25250c3b9e36.PNG)
.

**Comment by Hypeism** [comment]
Hello. Thank you for using the Heavy Division Mod. In order to activate LNAV you need to press the "ACTIVATE" button on the RTE page and then confirm by pressing the "EXEC" button once it turns green. I hope this helps.

よろしくお願いします,
Yoshi Dev Team

**Comment by kimidori1000** [comment]
English
Thank you for taking the time to answer.

I just tried it and sure enough, after I finished entering the FMC, I pressed the "ACTIVATE" button on the RTE page and after it turned green, I pressed the "EXEC" button and sure enough, I was able to activate LNAV.

I think I was complicating matters even more because there was a time when LNAV was usable even when I usually flew with a B747-8 or when I inserted a B78XH and followed the same procedure.
In the case of the B747-8 and the B787-10 without mod, I was able to turn on LNAV as soon as I finished setting up the FMC.

In any case, thank you very much for your answer.

P.S. The picture of the ANA paint job in your profile picture is cool, I like the ANA paint job too.

Japanese
わざわざ回答していただきありがとうございます。

今試したところ確かにFMCを入力し終わってからRTEページの「ACTIVATE」ボタンを押して、緑色になってから「EXEC」ボタンを押すと確かにLNAVを有効出来るようになりました。

普段B747-8で飛んでいたり、B78XHを入れて同じ手順をした場合でもLNAVが使えていた時期があったので余計に問題をややこしくしていたのだと思います。
B747-8とmod無しのB787-10の場合FMCを設定し終わったらすぐLNAVをオンに出来ていたので。

なんにせよ、回答していただきありがとうございました。

追伸 プロフィール画像のANA塗装の写真カッコいいですね、私もANA塗装が好きですよ。

**Comment by Hypeism** [comment]
Any time! Glad it worked :) feel free to join us on the Heavy Division discord server if you need help more quickly, as we watch that chat more often. 

You can join using this link: https://discord.gg/et7wVw35

Happy flying!
Yoshi 

もちろん、LNAVが使えってきて嬉しいです　:)。　まだ質問があれば、Heavyというdiscordサーバーが参加できます。私たちGitHubより早く支援ができます。私も、ANA好きです。アメリカ人だけど、一番好きな航空会社です。

(すみません、4年間日本語を勉強しておりますから、上には間違いがあるかもしれません)

ありがとうございます、
吉田
