### ISSUE TITLE
Issues with SU9 Beta - Mod Unusable

### ISSUE THREAD

**Issue by hmsilven** [Heavy-Division/B78XH#212]
Hi, I have been trying to use the mod with the latest beta SU9 but I cannot even start a flight because the FMC is not usable. It does not recognize the airport and importing the flightplan from SimBrief is not working, it only imports the departure and arrival airports, the route is empty. I can fly a complete planned flight without the mod. Is there anyone testing the mod against the new SU?

**Comment by Hypeism** [comment]
Could you please provide more information such as a video so we can understand the issue? I have just loaded in the SU9 Development version into the SU9 beta and was able to import and use a flightplan from simbrief with 0 issue.

**Comment by AAS1965** [comment]
Could i please ask how to go about downloading the patch for SU9 Beta compatibility?

**Comment by NakajimaYoshi** [comment]
Delete the current version of the mod in your community folder and download the SU9 compatible version from here or in the discord.
