### ISSUE TITLE
VNAV inoperative, No thrust after using reverse on runway, Constant overspeed at cruise level

### ISSUE THREAD

**Issue by Arcodacalheta** [Heavy-Division/B78XH#224]
1. **VNAV:** When using VNAV after reaching my cruise level, the plane - after stabilizing at FL350 - would after a few minutes suddenly climb beyond the selected flight level. The only remedy I found was to select altitude hold and not use VNAV at all.
2. **Constant overspeed at cruise level:** Apparently the speed calculation at the flight level (FL350) was wrong since it indicated a M0.95 which is obviously too fast, when manually reducing it to M0.82, I was still too fast, to be out of the alarm zone I had to throttle back to M0.74, which was too slow, the compromise was M0.82 with the constant alarm on for my 11 hour flight...
3. **Airplane stuck on the runway after using reverse thrust:** After landing and stopping the airplane on the runway using F2 and going to F1, no trust was available any more, the AutoBrake was OFF, Reverse was OFF, throttles were moving correctly, but the airplane was stuck, I had to slew to the gate.

**Comment by nakajimayoshi** [comment]
@Arcodacalheta Please Resubmit with video using the new issues system and the current version of the mod
