### ISSUE TITLE
AP won't follow FD pitch while VNAV Mode is enabled

### ISSUE THREAD

**Issue by mattlm0831** [Heavy-Division/B78XH#228]
I am having intermittent VNAV functionality issues. Whenever the issues are present, the FD indicates the horizon as the desired pitch (regardless of phase of flight), but doesn't follow that pitch, and I can put in as much elevator input as I want, without the AP disconnecting.

**Comment by nakajimayoshi** [comment]
@mattlm0831 If the issue is still occurring, please resubmit the issue using the new issues system with video.
