### ISSUE TITLE
CTD after the last ZIP download

### ISSUE THREAD

**Issue by dudsha** [Heavy-Division/B78XH#234]
When I go back to the previous version everything is fine, with the new version I get crash to desktop :-(
Windows and all drivers are updated.

**Comment by pr0f3ss** [comment]
I have tested the latest release, it works for me flawlessly. Your issue was probably related to the sim itself as around at this time many people experienced CTDs (when having enabled live weather). Asobo's official fix is to update to the newest Windows version and restart your PC.

**Comment by dudsha** [comment]
Thank you.
It works fine now :-)
