### ISSUE TITLE
auto throttle

### ISSUE THREAD

**Issue by chrisbailey22** [Heavy-Division/B78XH#240]
### Aircraft Version

Stable

### Build info

```json
{
    "package_version": "0.1.14",
    "fms_man_version": "HD-P000-1-14-STA-BAK",
    "fms_bak_version": "HD-C000-1-14-STA-BAK"
}
```

### Describe the bug

when i apply auto throttle and by pressing the butting and have the two levers for auto throttle set it will stay solid for a while than strart blinking than it turn its self off 

### Expected behavior

it should stay solid and keep intend flgight speed

### Steps to reproduce

flipped both lever
pressed at button by speed dial
stays steady than blinks than turn of

**Comment by nakajimayoshi** [comment]
AT sticking is a known issue. 

https://github.com/Heavy-Division/docs/blob/main/docs/B78XH/support/reported-issues.md
