### ISSUE TITLE
Aisle Stand FLOOD knob is INOP or does not control the light

### ISSUE THREAD

**Issue by kimlada** [Heavy-Division/B78XH#252]
### Name

Aisle Stand FLOOD knob

### Description

Aisle Stand FLOOD knob is INOP or does not control the light

**Comment by kimlada** [comment]
fixed 64c8dbda6d2943e38daf8b782ec3b16d43b715e8

**Comment by rabsp9** [comment]
The Functionality is working, but its backlight is not working. 
![Screenshot 2022-11-03 140332](https://user-images.githubusercontent.com/54253466/199641930-a8b38730-1b03-425e-a522-cde7fe572c89.jpg)

Off in the GA Version:
![Screenshot 2022-11-03 141651](https://user-images.githubusercontent.com/54253466/199641977-206e7b98-1d3f-44c8-ac57-1b4c647cd347.jpg)
Turn on the backlight in the GA version makes the dial backlight work too.
![Screenshot 2022-11-03 141737](https://user-images.githubusercontent.com/54253466/199641981-d1b4b648-c249-44fd-bcc4-d3b26c4a5b20.jpg)

**Comment by rabsp9** [comment]
This is the GA functionality.

https://user-images.githubusercontent.com/54253466/199642279-0bb16553-138c-4343-9575-4a16456f731e.mov

**Comment by rabsp9** [comment]
This is the New  Experimental. 

https://user-images.githubusercontent.com/54253466/199643697-6d6a550f-ea8e-4052-9a62-464cb77e03e9.mov

**Comment by rabsp9** [comment]
All working ok: Passed
