### ISSUE TITLE
V/S not being shown on the tape

### ISSUE THREAD

**Issue by ko-zone** [Heavy-Division/B78XH#269]
### Aircraft Version

Experimental

### Build info

```json
{
    "package_version": "0.1.15-16",
    "fms_man_version": "HD-P000-1-15-16",
    "fms_bak_version": "HD-C000-1-15-16"
}
```

### Describe the bug

V/S is not showing on the new PFD
![image](https://user-images.githubusercontent.com/70115175/203929280-39973660-3020-41b6-9e05-058108aac55a.png)

### Expected behavior

Expected V/S to be shown when the climb/descent gradient was great enough.

### Steps to reproduce

1. Load into the sim
2. Start Climbing/Descending
3. Observe V/S

### Discord Username (optional)

KO#2134

**Comment by kimlada** [comment]
Fixed
