### ISSUE TITLE
Interference with  Flysimware 414 EFB

### ISSUE THREAD

**Issue by topcat1952** [Heavy-Division/B78XH#274]
### Aircraft Version

Development

### Build info

```json
{
    "package_version": "0.1.15-5",
    "fms_man_version": "HD-P000-1-15-5",
    "fms_bak_version": "HD-C000-1-15-5"
}
```

### Describe the bug

When the HD B787XH DEV is installed using the MSFS Community Downloader, the EFB in the Flysimware 414 will not allow any of the boxes in the setup screen to be selected. In addition, unable to choose any of the other EFB screens. If I uninstall the HD B787XH DEV, then I can choose the Flysimware 414 EFB options without any issue.

### Expected behavior

Should have ability to use (i.e. check/choose) the Flysimware 414 EFB as I can do when the 787 is not installed.

### Steps to reproduce

1. I could not select any of the items in the 414 EFB after an earlier update (this past fall) of the 787. Consequent updates of the HD B787XH DEV have not fixed the  problem in the 414 up to and including the 2022/12/21 update.
2. After each HD B787XH DEV update install, I checked the EFB in the 414 and was unable to select any of the options. Uninstalling the latest update restored the 414 EFB ability to work correctly.
3. Checking the MSFS Forums is where I found out the HD B787 was the issue. HD is supposed to fix the issue but that has not yet happened as of the Dec 21 update.

### Discord Username (optional)

topcat1952

**Comment by nakajimayoshi** [comment]
Have you tried the experimental version? Most of the model behaviors have been completely rewritten to custom ones to avoid conflicts like this. #242

**Comment by topcat1952** [comment]
Worked perfectly! Thanks so much for the advice. I can now use both aircraft.

 �

Denny Knepper

Newville, PA 17241

 ***@***.***> ***@***.***

 �
