### ISSUE TITLE
Can't load flightplan in the air

### ISSUE THREAD

**Issue by matssederholm** [Heavy-Division/B78XH#276]
### Aircraft Version

Stable

### Build info

```json
{
    "package_version": "0.1.14",
    "fms_man_version": "HD-P000-1-14-STA-BAK",
    "fms_bak_version": "HD-C000-1-14-STA-BAK"
}
```

### Describe the bug

Flightplan is not possible to load or create in the air after loading a flight
- Loading a SB flightplan is blocked / has no effect
- Creating a flightplan is blocked as origin and dest is enterable

### Expected behavior

 Loading a SB flightplan should populate the FMS with the latest SB flightplan just as it works on ythe ground

### Steps to reproduce

1 Create a flight with a sb flightplan
2 Take off and save the flight
3 Load the flight and try to load the SB flightplan or create a new one

### Additional info (optional)

Also the Route page is blocked so that no origin or dest is editable making a flightplan completely impossible to create and a long distance flight pretty useless.

### Discord Username (optional)

Mats Sederholm#3315

**Comment by nakajimayoshi** [comment]
Hey there. You posted the layout.json, not the build info. Can you post the contents of B78XH.json in the html_ui folder? Thanks

**Comment by matssederholm** [comment]
FYI: Latest DEV have the same problem

**Comment by kimlada** [comment]
1) Loading FP from SimBrief does not make in air does not make sense because the aircraft will have completely wrong fuel block.
2) It is not true that it is not possible to insert destination and FP in midair. You just not able to add ORIGIN because you spawn midair so you have NO ORIGIN...
