### ISSUE TITLE
Your ASOBO_GT_Interaction_NoInteraction extension breaks WB/JPL152 mod.

### ISSUE THREAD

**Issue by Wombii** [Heavy-Division/B78XH#284]
### Aircraft Version

Stable

### Build info

```json
{
    "package_version": "0.1.15",
    "fms_man_version": "HD-P000-1-15-STA",
    "fms_bak_version": "HD-C000-1-15-BAK"
}
```

### Describe the bug

With our updated WB-Sim/JPLogistics cessna 152 mod we rely on the default behaviour of ASOBO_GT_Interaction_NoInteraction. Your extension of this template breaks it for us.

https://flightsim.to/file/2246/jplogistics-c152-enhancement-mod
With both the release version of the B787HX and the wb/jpl 152 installed at the same time, the 152 tablet goes blank when moused over.

Editing your nointeraction template version to have the default section outside the switch/case section makes our problems go away. Please consider if this works for you too.

This edit seems to solve it:
[Interactions.txt](https://github.com/Heavy-Division/B78XH/files/10529605/Interactions.txt)

### Expected behavior

Expected behaviour is for the template to have the same default behaviour :)

### Steps to reproduce

Install b787xh + wb/jpl 152. 
Load in wb/jpl 152. Open tablet located between seats. Try to mouseover tablet screen and it will be blank. 

Replace the \B78XH\ModelBehaviorDefs\Heavy\Extensions\Interactions.xml content.
Restart sim or quick reload in behaviourdebug. Tablet now works. 

### Discord Username (optional)

WombiiO_o#9000

**Comment by bagolu** [comment]
It breaks other mods too (payware & freeware)
My mods are impacted the same way as the wb/jpl 152 : 
https://flightsim.to/file/40194/cessna-172sp-skyhawk-as1000-improvement
https://flightsim.to/file/42097/rf172-reims-rocket-cessna-r172-hawk-xp-ii

**Comment by nakajimayoshi** [comment]
Have you attempted this with the experimental or only the development version? All model behaviors in the experimental share 0 names or templates with default aircraft.
