### ISSUE TITLE
PFD Has Black Background for 2-3 Minutes on Warm Runway Start

### ISSUE THREAD

**Issue by fbiganski** [Heavy-Division/B78XH#285]
### Aircraft Version

Stable

### Build info

```json
Downloaded several days ago from Github and re-downloaded again this morning. It's not the lite version but the full version 1.15.
```

### Describe the bug

PFD's & MFD's have a black background for about 4-5 minutes, then will suddenly display properly.  The displays will flash/look correctly for a millisecond after clicking "Ready to Fly".

I just started flying the 787-10 so I haven't yet graduated to begin from a cold start, but this issue occur whether sitting on tarmac at end of runway or during flight. 

I "think" the time for the displays to work properly vary as well. Sometimes they display correctly after 2-3 minutes but other times it can take 6-8 minutes.

The issue occurs when sitting on tarmac or during flight, and it occurs with MSFS default liveries as well.

I have a clean system with very few other mods, but I do use you other WT display mods for the CJ4 and Grand Caravan.

![image](https://user-images.githubusercontent.com/19510057/215680191-8224d977-f802-4d18-831b-b299e5946577.png)

### Expected behavior

Displays should immediately display properly from warm start on runway.

### Steps to reproduce

Clickrf "Ready to Fly" button and immediately, the cockpit PFD displays are not lite properly.

### Additional info (optional)

I really don't use Discord (Boomer hasn't figured it out yet).

### Discord Username (optional)

PacmanPilot#0167

**Comment by nakajimayoshi** [comment]
The displays are like this because the irs hasn't been aligned yet. You can instantly align them from the fmc menu by going to HEAVY->IRS MENU->FORCE ALIGN. Also the build info can be found in the htmlui/B78XH.json file.
