### ISSUE TITLE
the download link is not working

### ISSUE THREAD

**Issue by alime4** [Heavy-Division/B78XH#297]
### Aircraft Version

Stable

### Build info

```json
i dont know what is this ?
```

### Describe the bug

the zip file is not wokring
i download it and its doesnt apear in flight simulator this in the stable file and the devolpment but the experimental the aircraft apear in the game but it has alot bugs like the aircarft doesnt load so i want soulation pls

### Expected behavior

i expecte to download the stable mode form the website then i take the b78xh folder  and put it in commutinty folder of the game then i launch the game and done 

### Steps to reproduce

1. i download the stable version from the heavy devision website 
2. i opened the zip folder and took the b78xh folder and grap it to the commutinty folder of the game
3. then i opened the game but i didnt found the plane

### References (optional)

.

### Additional info (optional)

.

### Discord Username (optional)

luko8708

**Comment by nakajimayoshi** [comment]
stable is deprecated and you need premium deluxe to use our aircraft
