### ISSUE TITLE
Direct to with SID

### ISSUE THREAD

**Issue by hergi12345** [Heavy-Division/B78XH#55]
Can’t get direct to work within SID waypoints. I set up the FMC for a flight from EGKK to EDDF, departure rwy 26L and the SID is LAM2X. The direct to function does not work if I for example want to go direct SUNAV or any other waypoint within the SID.

The direct to function does seem to work well between the rest of the route waypoints and the STAR waypoints, but for some reason not with the SID waypoints.

And by the way the climb phase seems to work very well now after the fixes so thanks for that!

**Comment by kimlada** [comment]
MSFS handles SID a bit wierd and for the reason SID is removed when you use DIRECT TO during departure right now.
There is difference how MSFS handles SID with autogenerated waypoints (D0, D1 and so on) and without the waypoints.

if you want to skip waypoints in SID, use DELETE for the waypoints as a workaround now.

We will try to figure out this problem in version 0.1.5.

**Comment by Zyonix007** [comment]
this is fixed in upcoming release. i think

**Comment by kimlada** [comment]
Fixed in experimental build
