### ISSUE TITLE
Possible conflict with Working Title G1000 since Sim Update 3

### ISSUE THREAD

**Issue by Dazzlercee** [Heavy-Division/B78XH#61]
I have narrowed down an issue relating to the WT G1000 to having the B78XH mod enabled.

When enabled the WT G1000 has a dead PFD and a non-functioning MFD. Disabling B78XH mod cures the problem completely.

**Comment by apolinski** [comment]
I have the G1000 mod installed and don't see any problem with the PFD or MFD.  G1000 working properly

**Comment by Dazzlercee** [comment]
I have just checked again, and with just the 78XH and the WT G1000 enabled the G1000 does not function. If I disable the 78XH the G1000 starts to work again.

I can enable every addon except the 78XH and the G1000 functions correctly.

With the 78XH:

![With 78XH](https://user-images.githubusercontent.com/73283456/110936574-02df0480-8329-11eb-8e1b-875478a95421.JPG)


Without the 78XH:

![Without 78XH](https://user-images.githubusercontent.com/73283456/110936667-286c0e00-8329-11eb-9bfd-c7a088ffd748.JPG)

**Comment by kimlada** [comment]
Confirmed for v0.1.5. G1000 sometimes does not start with v0.1.5

Should be fixed in DEV version (v0.1.6+). Tested DEV version with G1000 mod and the problem has never appeared.
