### ISSUE TITLE
Missing several features after Sim Update 3

### ISSUE THREAD

**Issue by apolinski** [Heavy-Division/B78XH#62]
I am not seeing several features that are supposed to be in the mod.  I do not have a working VNAV page. Page only shows the word "untitled".  I do not have functioning IRS (beyond default).  I'm not sure what else I am missing. But my install doesn't look like the demo pictures on flightsim.to.

**Comment by kimlada** [comment]
IRS is not public yet.

I tested VNAV with SIM UPDATE 3 and i had no problem with VNAV pages.

"Untitled" means that the page script is corrupted. Try to redownload the mod or try download DEV version from GitHub repository.

**Comment by apolinski** [comment]
I've tried installing the mod several times.  Where is the DEV version? I don't see a dev branch.

**Comment by apolinski** [comment]
Are there any confirmed conflicts between this and other mods?  This is the only 787 mod I have

**Comment by apolinski** [comment]
Ok, I tried downloading direct from the main branch and re-installed and it seems to work.  Not sure why the zip files from flightsim.io and the release version here had issues.  Thanks for the great work! Even without the VNAV the 787 has been working fantastic.

**Comment by kimlada** [comment]
We do not have dedicated branch for DEV build now. MAIN branch is DEV build. I have tested released v0.1.5 from flightsim.to and i have no problem with the release. I do not really know why you had the problem with the released version, but it is good to hear that the DEV build fixed the problem.
