### ISSUE TITLE
Too nose high 

### ISSUE THREAD

**Issue by tjugpal** [Heavy-Division/B78XH#67]
Hello, I find that using this mod causes the aircraft to have too high an approach angle on final. I am not sure if this mod is compatible with the XE version. Thanks.

**Comment by kimlada** [comment]
What is your configuration and payload???

**Comment by tjugpal** [comment]
I usually balance it with payload first, and then add in the fuel. This way
the CG is never offset by too much as the fuel is burnt.

I believe this could be an issue with the default 787, as using the other
mod 787 doesn't cause this problem with the same payloads and fuel.

Thanks

**Comment by kimlada** [comment]
What is your targeted CG for approach, what is your payload, what is your approach speed, what flaps do you use for approach and for final, what is your trim?? What is the aircraft configuration when you enable APP (if you use APP). What is weather conditions, especially wind and wind direction? Could you record a video of your approach??

Contact me on discord if you can. It will be faster...
