### ISSUE TITLE
HDG/SPEED +\- 10degree bug

### ISSUE THREAD

**Issue by jonnoc1** [Heavy-Division/B78XH#71]
When scrolling / clicking either HDG or speed. Only goes by figures of +/- 10

**Comment by kimlada** [comment]
What peripherals do you use??

**Comment by jonnoc1** [comment]
Thrustmaster Airbus quadrant, mouse & keyboard. Saitek radio panel. Class echo.

**Comment by Zyonix007** [comment]
Did asobo fix this lastest update?

**Comment by kimlada** [comment]
This need to be fixed by Asobo
