### ISSUE TITLE
transition lost 

### ISSUE THREAD

**Issue by Giankynav** [Heavy-Division/B78XH#73]
non so se è dovuto a causa dell'aggiornamento di msfs, ho provato l'ultima versione, e tutte le transition sia delle sid che delle star spariscono, ora per le sid, si può ovviare con un dir TO , ma per le star, tutti gli approch vanno in missed, ho provato ad inserirle senza la mod e le trova, peccato, perché ho trovato utile le impostazioni del ratio di salita  e di discesa...ma è anche vero che il 787 ancora deve essere sviluppato bene da asobo...

**Comment by kimlada** [comment]
Fixed in experimental build
