### ISSUE TITLE
[BUG] Fuel Burn Consumption

### ISSUE THREAD

**Issue by dcherrie** [Heavy-Division/B78XH#83]
The aircraft burns significantly less fuel than what is expected according to SimBrief.

EBBR to CYVR took off with 163,000 lbs and should have landed with 17,600 lbs but still had over 85,000 pounds.

I work on the Salty 747 and haven't really used the 787 much but I assume you don't have access to the engines.cfg to fix it?

**Comment by kimlada** [comment]
Yeah it is not possible to fix it by engines.cfg file but i was thinking about that and i think that i found a way how to workaround the limitation.
