### ISSUE TITLE
Edit FL and Speed in first WP in a STAR or on the Route (for use of VNAV)

### ISSUE THREAD

**Issue by SandaleAir** [Heavy-Division/B78XH#92]
Hello,

in some STAR's we need to edit FL or Speed of the first WP of the STAR. Otherwise the ATC can advise you to reach a FL at another specific Waypoint on the the Route. So it were also nice to edit a WP on the Route in this case. Is it possible to make this in the future?

Gretings,
Sascha.

**Comment by SandaleAir** [comment]
Hello,

had someone read this request?

Greetings,
Sascha.

**Comment by kimlada** [comment]
This is already impemented in Experimental build....

**Comment by SandaleAir** [comment]
Hello,

thanks for your answer.

i've checked it again. There are two possibilities.

If you already have the first waypoint of the STAR in the route, the altitude and speed cannot be changed after inserting the STAR.

If you delete this waypoint before inserting the STAR then it works.

Wouldn't it generally make sense if you could change altitude and speed at every waypoint on the route?

Greetings,
Sascha.

**Comment by kimlada** [comment]
Hi,

Boeing does not allow change waypoint constraints for enroute waypoints.

**Comment by SandaleAir** [comment]
Hello,

in my case was the Problem that the first STAR WP had a constraint. If i had it in the FMS as last enroute WP so i can't change it. So i had do delete it and plan the arrival after that. I fly on Vatsim so in some cases i didn't know the arrival long before i'm reaching the last enroute WP.

Greetings,
Sascha.

**Comment by kimlada** [comment]
Hello,

still do not get the problem... During CRZ you can do CRZ DES or CRZ CLB if ATC want you to change FL...

During descent if you are not allowed to descend because of ATC you can block descent by MCP altitude window and when ATC allow you descent you can change MCP altitude window and push altitude intervention...

**Comment by kimlada** [comment]
Or are you only talking about the problem that FMC does not allow change constraint for active waypoint???
