### ISSUE TITLE
Discord invite invalid

### ISSUE THREAD

**Issue by AviationSpotter** [Heavy-Division/B78XH#93]
As you see above the discord link is not valid (possibly expired). Apologies for filling your issues with this issue but I have no other way to notify you of this issue. If you could fix the invite I'll be on my way. Thanks!

**Comment by mjchernis** [comment]
Same here..probably an easy fix too!

**Comment by AviationSpotter** [comment]
> Same here..probably an easy fix too!

@mjchernis I've contacted them via discord and should be fixed.. soon. I just wish they checked their issues more often for cases like these. If you need a discord invite you can join here: https://discord.gg/VWhmVwjqVA

**Comment by mjchernis** [comment]
Thanks much!

**Comment by kimlada** [comment]
fixed
