### ISSUE TITLE
not loading flight plan correctly

### ISSUE THREAD

**Issue by ahad122** [Heavy-Division/B78XH#94]
Noticed that when I load a flight plan from the main screen and then start the flight, I need to configure the route again but I do see the flight in nav tool. Please look at the images below, thanks!
I did pull the latest from `FPSYNC-LEGS-FIX`

![image](https://user-images.githubusercontent.com/1811007/119268483-3bb91680-bbc1-11eb-90ed-70c9a3c8f2e7.png)

![image](https://user-images.githubusercontent.com/1811007/119268446-0a404b00-bbc1-11eb-93c3-33564d15d921.png)

**Comment by kimlada** [comment]
This is normal behavior... This function require FPSync turned on... but FPSync is not recommended because it cause problems with DIRECT TO...
