### ISSUE TITLE
PFD and MFD freezing Mid-Flight

### ISSUE THREAD

**Issue by Secretme78** [Heavy-Division/B78XH#95]
Just after sim update 4 when I've tried to do a flight right after takeoff the pfd and mfd freeze and stop updating the display data. The drop-down HUD will still work fine the the flight directors and the nav lines with stop moving. Tried changing the refresh rate and everything. Anyone maybe know what has caused this?

**Comment by Xellli** [comment]
yes i have the same

**Comment by sigvek** [comment]
Yes I have the same.
![image](https://user-images.githubusercontent.com/8478625/120116225-71449d80-c187-11eb-83f1-d42cbe14878a.png)

**Comment by 1ancaster** [comment]
I am also having this problem with loss of the whole flight plan and waypoints so will appreciate any comments 
Thank you

**Comment by demariners** [comment]
Same thing here!

**Comment by kimlada** [comment]
Use Experimental  build... Only experimental build has SU4 patch...

**Comment by 1ancaster** [comment]
Which of the releases is the experimental build which contains SU4? It's not clear if there is a release since SU4.
Thank you

**Comment by kimlada** [comment]
Experimental is WTFPMMEPOC branch

https://github.com/Heavy-Division/B78XH/archive/refs/heads/WTFPMMEPOC.zip

**Comment by sigvek** [comment]
I built WTFPMMEPOC myself earlier today and have flown 3 flights with no issues.
